server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: order
          uri: http://localhost:8081
          predicates:
            - Path=/orders/**
        - id: delivery
          uri: http://localhost:8082
          predicates:
            - Path=/deliveries/**
        - id: customer
          uri: http://localhost:8083
          predicates:
            - Path=/customers/**,/myPages/**
        - id: bookInventory
          uri: http://localhost:8084
          predicates:
            - Path=/books/**,/deliverables/**,/stockInputs/**
        - id: coupon
          uri: http://localhost:8085
          predicates:
            - Path=/coupons/**
        - id: myCoupon
          uri: http://localhost:8086
          predicates:
            - Path=/myCoupons/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: order
          uri: http://order:8080
          predicates:
            - Path=/orders/**
        - id: delivery
          uri: http://delivery:8080
          predicates:
            - Path=/deliveries/**
        - id: customer
          uri: http://customer:8080
          predicates:
            - Path=/custormers/**,/myPages/**
        - id: bookInventory
          uri: http://bookinventory:8080
          predicates:
            - Path=/books/**,/deliverables/**,/stockInputs/**
        - id: coupon
          uri: http://coupon:8080
          predicates:
            - Path=/coupons/**
        - id: myCoupon
          uri: http://mycoupon:8080
          predicates:
            - Path=/mycoupons/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080

